= Table.TransformColumnTypes(#"Filtered Rows",
        {{"UID", type number}, {"Name", type text}, {"Position", type text}, {"Age", type number}, {"Height", type text}, {"Weight", type text}, {"Inf", type text}, {"Club", type text}, {"Division", type text}, {"Nat", type text}, {"2nd Nat", type text}, {"Home-Grown Status", type text}, {"Personality", type text}, {"Media Handling", type text}, {"Wage", type text}, {"Transfer Value", type text}, {"Asking Price", type text}, {"Preferred Foot", type text}, {"Yel", type number}, {"xG", type number}, {"Starts", type number}, {"Red", type number}, {"PoM", type number}, {"Pen/R", Percentage.Type}, {"Pens S", type number}, {"Pens Saved Ratio", Percentage.Type}, {"Pens Saved", type number}, {"Pens Faced", type number}, {"Pens", type number}, {"Mins", type number}, {"Gls/90", type number}, {"Conc", type number}, {"Gls", type number}, {"Fls", type number}, {"FA", type number}, {"xG/90", type number}, {"xG-OP", type number}, {"xA/90", type number}, {"xA", type number}, {"Con/90", type number}, {"Clean Sheets", type number}, {"Av Rat", type number}, {"Mins/Gl", type number}, {"Ast", type number}, {"Hdrs A", type number}, {"Apps", type text}, {"Tck/90", type number}, {"Tck W", type number}, {"Tck A", type number}, {"Tck R", Percentage.Type}, {"Shot/90", type number}, {"Shot %", Percentage.Type}, {"ShT/90", type number}, {"ShT", type number}, {"Shots Outside Box/90", type number}, {"Shts Blckd/90", type number}, {"Shts Blckd", type number}, {"Shots", type number}, {"Svt", type number}, {"Svp", type number}, {"Svh", type number}, {"Sv %", Percentage.Type}, {"Pr passes/90", type number}, {"Pr Passes", type number}, {"Pres C/90", type number}, {"Pres C", type number}, {"Pres A/90", type number}, {"Pres A", type number}, {"Poss Won/90", type number}, {"Poss Lost/90", type number}, {"Ps C/90", type number}, {"Ps C", type number}, {"Ps A/90", type number}, {"Pas A", type number}, {"Pas %", Percentage.Type}, {"OP-KP/90", type number}, {"OP-KP", type number}, {"OP-Crs C/90", type number}, {"OP-Crs C", type number}, {"OP-Crs A/90", type number}, {"OP-Crs A", type number}, {"OP-Cr %", Percentage.Type}, {"Off", type number}, {"Gl Mst", type number}, {"K Tck/90", type number}, {"K Tck", type number}, {"K Ps/90", type number}, {"K Pas", type number}, {"K Hdrs/90", type number}, {"Int/90", type number}, {"Itc", type number}, {"Sprints/90", type number}, {"Hdr %", Percentage.Type}, {"Hdrs W/90", type number}, {"Hdrs", type number}, {"Hdrs L/90", type number}, {"Goals Outside Box", type number}, {"xSv %", Percentage.Type}, {"xGP/90", type number}, {"xGP", type number}, {"Drb/90", type number}, {"Drb", type number}, {"Distance", type number}, {"Cr C/90", type number}, {"Cr C", type number}, {"Crs A/90", type number}, {"Cr A", type number}, {"Cr C/A", Percentage.Type}, {"Conv %", Percentage.Type}, {"Clr/90", type number}, {"Clear", type number}, {"CCC", type number}, {"Ch C/90", type number}, {"Blk/90", type number}, {"Blk", type number}, {"Asts/90", type number}, {"Aer A/90", type number}, {"NP-xG", type number}, {"NP-xG/90", type number}, {"xG/shot", type number}},
        "fr-FR")